### ISSUE TITLE
Zhi An tasks tracker

### ISSUE THREAD

**Issue by ngzhian** [midichrolians/midichrolian-ios#88]
- [x] delete sample
- [x] see which page is selected (#93 )
- [x] nicer looking pads #84 
- [x] preview animation #71
- [x] controls for audio (loop and 1 time)
- [x] controls for recording #93 #87 
- [x] prompt for animation name #107
